function Plot_motion(x,d,N)
% plot positions of the agents to see if the dynamics is correct;
% Input:
%   time - adaptive time instances generated by solver ode113
%   x    - trajectory data; size =  (d x N) x time
% (c) XXXX


% Note: state vector x   - the state vector dN x 1; 
%        [x_1(1), ..., x_N(1), ... , x_1(d),..., x_N(d)]^T

figure;
L = size(x,2);   % time steps
flag=1;
if d==2
    for step = 1:1:L   % plot only the first 2 coordinates
        xtemp = reshape(x(1:d*N,step),d,N); x1 = xtemp(1,:); x2 = xtemp(2,:);
        plot(x1, x2,'o');     axis([-4,4,-4,4]);
        %titleT = strcat('time ', num2str(time(step), '%.3f'));   title(titleT);
        pause(0.02);
    end
    
else
    for i=1:N
        plot(1:L,x(i,:),'Linewidth',2);  hold on   xlabel('Time'); ylabel('particles');
    end
    hold off;
 %titleT = strcat('time ', num2str(time(end), '%.3f'));   title(titleT);
end

return