% Authored by Jinchao Feng and Sui Tang
% make_table.m
% Produces two paper-ready table files mirroring the figure structure:
%   ../table_OD.tex
%       (ODNS d=1 and d=2 predict-window errors, with shared methodology paragraph)
%   ../table_CS.tex
%       (CSNS1 cut-off and CSNS2 smooth predict-window errors)
%
% Headline metric in every cell: relative max-time trajectory error on the
% prediction window (5, T_f] for the FRESH initial condition, mu +/- s
% across T = 10 trials.
clear; close all;

M_list  = 1:10;
data_dir = '../trajectory_data';
out_dir  = '..';

% Each block describes one paper sub-table. file_prefix loads from the
% on-disk .mat naming; display_label is what the paper calls the experiment.
groups = { ...
  struct('out','table_OD.tex','section','ODNS', ...
         'kernel_desc','step kernel $\phi(r)=\mathbf{1}_{[0,0.5)}(r)+0.1\,\mathbf{1}_{[0.5,1)}(r)$', ...
         'sub', { { ...
           struct('label','ODNS, $d=1$','file_prefix','ODNS1','dim_token','d1', ...
                  'nsr',[0 0.25 0.5 0.75 1], 'tag','tab:OD-d1-traj'); ...
           struct('label','ODNS, $d=2$','file_prefix','ODNS2','dim_token','d2', ...
                  'nsr',[0 0.25 0.5 0.75 1], 'tag','tab:OD-d2-traj') } }); ...
  struct('out','table_CS.tex','section','CSNS', ...
         'kernel_desc','two Cucker--Smale interaction kernels (cut-off and smooth-decay)', ...
         'sub', { { ...
           struct('label','CSNS1: cut-off $\phi(r)=\mathbf{1}_{[0,0.5]}(r)$','file_prefix','CSNS2','dim_token','d2', ...
                  'nsr',[0 0.1 0.2 0.3 0.4 0.5], 'tag','tab:CS-cutoff-traj'); ...
           struct('label','CSNS2: smooth $\phi(r)=1/(1+r^2)^{1/4}$','file_prefix','CSNS1','dim_token','d2', ...
                  'nsr',[0 0.025 0.05 0.075 0.1], 'tag','tab:CS-smooth-traj') } }) };

% Compact "factored exponent" cell formatter (defined as anonymous via helper at end of file).
fmt_cell = @(m,s) compact_cell(m,s);

for g = 1:numel(groups)
    G = groups{g};
    fid = fopen(fullfile(out_dir, G.out),'w');
    fprintf(fid, '%% auto-generated by make_table.m -- %s trajectory prediction error\n\n', G.section);

    for s = 1:numel(G.sub)
        S = G.sub{s};
        nsrs = S.nsr;

        % --- load (M x nsr) matrices ---
        mu_pred = NaN(numel(M_list), numel(nsrs));
        sd_pred = NaN(numel(M_list), numel(nsrs));
        for mi = 1:numel(M_list)
            for ki = 1:numel(nsrs)
                fname = sprintf('%s/%sN100%sM%dL6sigma%s.mat', data_dir, ...
                                S.file_prefix, S.dim_token, M_list(mi), num2str(nsrs(ki)));
                if ~exist(fname,'file'), continue; end
                D = load(fname);
                mu_pred(mi,ki) = mean(D.errortrajs_test(3,:));
                sd_pred(mi,ki) = std (D.errortrajs_test(3,:));
            end
        end

        % --- emit table ---
        fprintf(fid, '\\begin{table}[!htb]\n\\centering\n');
        fprintf(fid, '\\caption{\\rev{%s. Relative max-time trajectory prediction error\n', S.label);
        fprintf(fid, '$\\mathrm{err}(\\mathcal{W}_{\\text{pred}})$ on the prediction window\n');
        fprintf(fid, '$(5,T_f]$, evaluated at a fresh initial condition. Rows: number of\n');
        fprintf(fid, 'training trajectories $M$; columns: noise-to-signal ratio\n');
        fprintf(fid, '$\\sigma_{\\text{nsr}}$. Each cell reports $\\mu \\pm s$ across $T=10$\n');
        fprintf(fid, 'independent trials.}}\n');
        fprintf(fid, '\\label{%s}\n', S.tag);
        fprintf(fid, '\\renewcommand{\\arraystretch}{1.15}\n\\setlength{\\tabcolsep}{4pt}\n\\footnotesize\n');
        colspec = ['c|' repmat('c', 1, numel(nsrs))];
        fprintf(fid, '\\begin{tabular}{%s}\n\\toprule\n', colspec);
        fprintf(fid, '\\multirow{2}{*}{$M$} & \\multicolumn{%d}{c}{$\\sigma_{\\text{nsr}}$} \\\\\n', numel(nsrs));
        fprintf(fid, '\\cmidrule(lr){2-%d}\n ', numel(nsrs)+1);
        for k = 1:numel(nsrs), fprintf(fid, ' & $%g$', nsrs(k)); end
        fprintf(fid, ' \\\\\n\\midrule\n');
        for mi = 1:numel(M_list)
            fprintf(fid, '%d', M_list(mi));
            for ki = 1:numel(nsrs)
                if isnan(mu_pred(mi,ki)), fprintf(fid, ' & ---');
                else,                     fprintf(fid, ' & %s', fmt_cell(mu_pred(mi,ki), sd_pred(mi,ki))); end
            end
            fprintf(fid, ' \\\\\n');
        end
        fprintf(fid, '\\bottomrule\n\\end{tabular}\n\\end{table}\n\n');
    end

    fclose(fid);
    info = dir(fullfile(out_dir, G.out));
    fprintf('wrote %s (%d bytes)\n', fullfile(out_dir, G.out), info.bytes);
end

%% ---- helpers (must come after all top-level code) ----------------------
% Compact "factored exponent" cell formatter: writes mu and sd at a shared
% scale 10^e (chosen from the larger of |mu|,|sd|), 1 decimal in the mantissa.
% e.g. mu = 1.13e-04, sd = 6.29e-05  ->  $1.1\!\pm\!0.6\!\cdot\!10^{-4}$
function out = compact_cell(mu, sd)
    if isnan(mu) || isnan(sd), out = '---'; return; end
    scale = max(abs(mu), abs(sd));
    if scale == 0, out = '$0$'; return; end
    e = floor(log10(scale));
    % bump exponent when mantissa would round up to 10.0 at 1-decimal display
    if scale * 10^(-e) >= 9.95
        e = e + 1;
    end
    mm = mu * 10^(-e);
    ss = sd * 10^(-e);
    if e == 0
        out = sprintf('$%.1f \\pm %.1f$', mm, ss);
    else
        % parentheses around mu +/- sd so the 10^e factor applies to BOTH
        out = sprintf('$(%.1f \\pm %.1f)\\!\\times\\!10^{%d}$', mm, ss, e);
    end
end
